### ISSUE TITLE
Python 3.10 Support

### ISSUE THREAD

**Issue by acd124** [chrisdewa/unbelipy#18]
### Summary

Add support for python 3.10 compatibility

### What is this for and why is it needed?

Currently in python 3.10 running methods results in the following type error

TypeError: As of 3.10, the *loop* parameter was removed from Condition() since it is no longer necessary

### Ideal solution

Research compatibility with this to see if code can be provided that works with both 3.8, 3.9, and 3.10, and if not look into providing a different version for 3.10.

### Checklist

- [X] I have searched the entire issue tracker, and have ensured this is not a duplicate.

**Comment by chrisdewa** [comment]
Thanks for bringing this to my attention. Please provide the full traceback of the exception

**Comment by acd124** [comment]
Traceback with full paths edited. The provided paths should be as specific as necessary
```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    loop.run_until_complete(main())
  File "python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "test.py", line 13, in main
    guild_leaderboard = await client.get_guild_leaderboard(guild_id)
  File "python3.10/site-packages/unbelipy/client.py", line 346, in get_guild_leaderboard
    return await self._request(
  File "python3.10/site-packages/unbelipy/client.py", line 586, in _request
    async with bucket_handler as bh:
  File "python3.10/site-packages/unbelipy/rate_limits.py", line 83, in __aenter__
    self.cond = self.cond or asyncio.Condition(loop=asyncio.get_running_loop())
  File "python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/locks.py", line 231, in __init__
    super().__init__(loop=loop)
  File "python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Condition() since it is no longer necessary
```

**Comment by chrisdewa** [comment]
Thanks, i submitted a commit ([5b4a38b](https://github.com/chrisdewa/unbelipy/commit/5b4a38be75aa4e88276afd8596e5bfef06254391)) that should take care of the problem. 

The Condition is used as a lock but in retrospective it should actually be a Lock since it never awaits a predicate, so it's probably going to be modified next.
